import "./globals.css"
import { Inter } from "next/font/google"
import { ThemeProvider } from "../src/components/theme-provider"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    /*
    icons: {
        icon: '/icons8-star-3d-fluency-96.png',
    },
    */
}

export default function RootLayout({ children }) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body className={inter.className}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
            {children}
        </ThemeProvider>
        </body>
        </html>
    )
}